server.port=8080
# ===============================
# DATABASE
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/security
spring.datasource.username=root
spring.datasource.password=123456@a
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# ===============================
# LOG
# ===============================
## Show error log + info log + debug log and output to database
log4j.rootLogger= DEBUG, DB
# Define the DB appender
log4j.appender.DB=org.apache.log4j.jdbc.JDBCAppender
# Set JDBC URL
log4j.appender.DB.URL=jdbc:mysql://localhost:3306/security
# Set Database Driver
log4j.appender.DB.driver=com.mysql.jdbc.Driver
# Set database user name and password
log4j.appender.DB.user=root
log4j.appender.DB.password=123456@a
# Set the SQL statement to be executed.
log4j.appender.DB.sql=INSERT INTO log (level, logger, message) VALUES ('1', '1', '1');
# Define the layout for file appender
log4j.appender.DB.layout=org.apache.log4j.PatternLayout